development:
  sessions:
    default:
      database: backbone_auth_development
      hosts:
        - localhost:27017
test:
  sessions:
    default:
      database: backbone_auth_test
      hosts: 
        - localhost:27017
